# NAME: Alex Chen
# EMAIL: achen2289@gmail.com
# ID: 005299047

CC = gcc
CFLAGS = -Wall -Wextra

default: lab1a

lab1a:
	$(CC) $(CFLAGS) -o lab1a lab1a.c

dist:
	tar -czvf lab1a-005299047.tar.gz lab1a.c Makefile README

clean:
	rm -f lab1a *.tar.gz