# NAME: Alex Chen
# EMAIL: achen2289@gmail.com
# ID: 005299047

.PHONY: default dist clean
.SILENT: 

default:
	rm -f lab3b
	ln lab3b.py lab3b
	chmod +x lab3b

dist:
	tar -czvf lab3b-005299047.tar.gz lab3b.py Makefile README

clean:
	rm -f lab3b *.tar.gz